### ISSUE TITLE
Grammar files generated in root directory

### ISSUE THREAD

**Issue by jonmaiga** [archmageirvine/joeis#6]
I cloned the repository on a Windows machine, then ran `ant jar` which complained on missing grammar files

```
>ant jar
Buildfile: C:\projects\standalone\joeis\build.xml

compile-grammar:

compile-src:
    [mkdir] Created dir: C:\projects\standalone\joeis\build.tmp\classes
    [javac] Compiling 141905 source files to C:\projects\standalone\joeis\build.tmp\classes
    [javac] C:\projects\standalone\joeis\src\irvine\math\expression\Sircon.java:22: error: cannot find symbol
    [javac]     final GrammarLexer lexer = new GrammarLexer(input);
```

I noticed that `compile-grammar` had generated the grammars into the root directory instead of `src/irvine/math/expression` (guessing the should end up here since I couldn't spot an generated source directory).

After moving the grammar files into the correct directory it worked.

I also hacked this into the `build.xml` which 'worked' but I guess package should suffice
```
      <arg value="-o"/>
      <arg value="src/irvine/math/expression"/>
```

**Comment by archmageirvine** [comment]
Yes, you are correct about where the generated class files should go.

Possibly a known issue with ANTLR, see [here](https://github.com/tunnelvisionlabs/antlr4ts/issues/303). The proposed change to `build.xml` breaks the build for Linux (resulting in output incorrectly generated into `src/irvine/math/expression/src/irvine/math/expression/`). Later versions of ANTLR (e.g. 10.1) have `-Xexact-output-dir` that might circumvent the problem, but that requires a newer Java compiler than I'm wanting to enforce).

**Comment by archmageirvine** [comment]
Ok, I upgraded to ANTLR 4.8 which provides the `-Xexact-output-dir` option. I also changed `Grammar.g4` itself to contain the package specification so that it is no longer needed in `build.xml`.  I've confirmed that the new version still works on Linux and would appreciate if you can try it on Windows.

**Comment by jonmaiga** [comment]
Great, yes it works on Windows as well!
